### ISSUE TITLE
Reconnection Subscription / Event Duplication

### ISSUE THREAD

**Issue by artdude543** [WatchBeam/carina#6]
It seems the auto reconnection is causing duplicate events to occur.

I noticed this today when debugging events and on production the server logged the hosting event way more than it should be doing so. This is open happening when a reconnection is occurring. Fresh instance are working as intended for obvious reasons.

I can guess that the event listener for messages / or the subscription to old events is firing too many times which is creating the duplication of events back to the callback.

Example: ![Screenshot](https://sx.artdude.uk/hotlink-ok/uVKs-5c393-1473203334.png)

(This is raw logging from the Carina callback on our host listener. I can only guess this is happening to all our callbacks listening to other events)

From revewing the code it seems when this [method](https://github.com/WatchBeam/carina/blob/master/src/socket.ts#L321) is called on a new socket the events or bound to that instance. Then when a reconnection is triggered it binding again to the new one but not cleaning out the old listeners for the previous socket.

**Comment by connor4312** [comment]
Is your code calling `.connect()` multiple times without `.close()`ing old sockets?

**Comment by artdude543** [comment]
Nope it's just called once and left alone to do it's thing.

**Comment by artdude543** [comment]
CC: @connor4312 @Doridian @ProbablePrime 

So this has happened again for the 6th today which is now leading to chat spam occurring in channels. I've done some more debugging / testing and this is definitely an issue with Carina or server side.

However I may of found the issue leading to the event spam. The Carina client is consistently getting `invalid error code` from the WS side [See Fig 1.] which is throwing and then leading to the dupe events. This is happening a lot now and Beam is the only site I'm seeing this error code from. I love Beam to death but these issues are causing problems upon problems and being told the same PDF response is leading to no where and this rate would lead to me needing to drop Beam support so I stay  sane.

You can see from our bot logs [See Fig 2.] the error being thrown and events being duped (bottom of the logs) But the curious thing is the `hello` response from the server is sent once from the socket (we have two sockets open at that time) but the "live" events are duped which leads me to think that maybe server side the same socket is being registered more than once to get the events. The same issue affects chat as in the issue here: https://github.com/WatchBeam/beam-client-node/issues/53 And the chat events are being duped. Again this does not happen on other sites we work with which use sockets. The only difference is that they don't use CDN protection such as CloudFlare.

The last option I have really is to not use the Beam provide modules and make my own modules to handle the errors easier / cleaner but this is a route I'd rather not take. Due to wanting to support Beam's own modules. I've done all the things I can to log / doc this error and this is reproducible each time with random error codes from somewhere. But I can't make a test to simulate the error. Due to how WS throws / handles the error causing a "fake" response is a pain.

Fig 1.
![Fig 1.](https://sx.artdude.uk/hotlink-ok/vsNp-db6ba-1474061012.png)

Fig 2.
![Fig 2.](https://sx.artdude.uk/hotlink-ok/NI6m-5e6bf-1474060931.png)

**Comment by artdude543** [comment]
I left in some more debug code last night. To which the same issue occurred and this time managed to create a duplication on mass till the bot crashed from a memory leak. The same issue again with the `1006` being thrown from the client. I reached out to other developers sent them all this information and they all respond as I'm trying to get across here that the issue is not my fault and that it's something going on with the connections to Beam.

The `1006` is thrown from the client on it's own when the `"close" control frame` is not sent down. Or the code is throw server side. This problem has nothing to do with the client anymore, unless a handler is added to deal with the issue. I can not reproduce on my own computer / network but my server which runs all the bot is consistently showing the fault. Before anyone jumps the gun I have disabled the servers firewalls / opened the bandwidth up more to test if the server was helping to cause this to the issue showing regardless of the server's state.

**Comment by connor4312** [comment]
Hey, sorry for the late response here, I just got back from vacation this week 😄 

The event duplication issue was a problem in Constellation itself. A fix for that was merged in https://github.com/WatchBeam/constellation/pull/18 and it has just been deployed.

@ProbablePrime said he followed up with you verbally regarding the 1006 issue, please work together to resolve the issue!

**Comment by ProbablePrime** [comment]
Thanks so much for your detailed report, Art :) Also following up regarding 1006 here for anyone interested.

According to some research the team did from github issues out in the wild 1006 is a WS Client error code thrown when a serverside connection is closed without a close frame.

Our modules should be handling these better. We should be able to mock this process and get some tests and code changes in place.

Thanks for hanging in there!

**Comment by artdude543** [comment]
@connor4312 @ProbablePrime Since the problem server side has been resolved a new / current issue has arisen. The callback on the subscribe method is being called more than one. I've debugged the events coming down on the socket and it's triggering the once. But then the callback is somehow being triggered more than once.

This might have something to do with the fact that the `event:live` https://github.com/WatchBeam/carina/blob/master/src/carina.ts#L74 is registered more than once and we sub to a batch of channels on a single socket. So that listener would be "emitted" each time over and over which could lead to the callback being called more than once. In theory this should _only_ be registered once to prevent rare cases and such. Along with lowering the memory overhead for the module.

I was debugging this on stream this morning and ruled out that it's my applications fault along with the constellation server. So this is a Carina issue.

**Comment by artdude543** [comment]
So I found a bug in my code which was contributing to the dupe events. However the issue in regards to the "live" event being registered on each subcribe could be looked into for performance matter. Since this module went from being light weight to pretty fat. Looking at improving the overheads on the module could be an idea. Also maybe some Observable love? 😉

**Comment by connor4312** [comment]
>  Also maybe some Observable love?

We're beginning to move our frontend towards Angular 2. Observable love is likely imminent ;)

**Comment by artdude543** [comment]
This is no longer an issue. (Well has not been now for a few updates now :P )
