### ISSUE TITLE
Releases out-of-date

### ISSUE THREAD

**Issue by xCausxn** [WatchBeam/carina#8]
Currently there is only version 0.3.1 on the releases, however this does not reflect the current stable version/npm version.

**Comment by ProbablePrime** [comment]
Can we automate this with jenkins.

https://github.com/toggl/toggldesktop/releases shows a bot submitting releases.

**Comment by connor4312** [comment]
My bad, I forgot to `--tags` my git push. @ProbablePrime this is automated with `np`, I just hadn't set it up on my work computer yet ;) 

I'll get this pushed as soon as I'm back on desktop

**Comment by ProbablePrime** [comment]
Ahh awesome

**Comment by connor4312** [comment]
Hey, so there actually were 0.4.x releases but Github hid them because there were not titled/tagged in the GUI, just pushed up from my local repo. I've titled the latest release and included a brief changelog.

**Comment by artdude543** [comment]
@connor4312 On the release you made it's `.open()` not `.connect()`

**Comment by ProbablePrime** [comment]
I updated the release notes.
